scsi: Re-add some SCSI definitions
These definitions were removed after OSRC source drop,
but still required:

  block/scsi_ioctl.c:574:8: error: use of undeclared identifier 'SCSI_IOCTL_GET_IDLUN'
                  case SCSI_IOCTL_GET_IDLUN:
                       ^
  block/scsi_ioctl.c:577:8: error: use of undeclared identifier 'SCSI_IOCTL_GET_BUS_NUMBER'
                  case SCSI_IOCTL_GET_BUS_NUMBER:
                       ^
  2 errors generated.

Signed-off-by: Hendra Manudinata <hendra@manudinata.me>