net: Add KNOX NCM guards
While compiling Kernel with KNOX NCM disabled,
we would see these errors:

  net/core/sock.o: In function `sock_set_dns_pid':
  /home/hendra/Androwee/NetHunter/r8q/out/../net/core/sock.c:703: undefined reference to `check_ncm_flag'
  net/core/sock.o: In function `sk_alloc':
  /home/hendra/Androwee/NetHunter/r8q/out/../net/core/sock.c:1683: undefined reference to `check_ncm_flag'
  net/netfilter/nf_conntrack_core.o: In function `nf_ct_add_to_dying_list':
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:485: undefined reference to `check_ncm_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:486: undefined reference to `knox_collect_conntrack_data'
  net/netfilter/nf_conntrack_core.o: In function `gc_worker':
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1251: undefined reference to `check_ncm_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1251: undefined reference to `check_intermediate_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1254: undefined reference to `get_intermediate_timeout'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1255: undefined reference to `knox_collect_conntrack_data'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1251: undefined reference to `check_ncm_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1251: undefined reference to `check_intermediate_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1254: undefined reference to `get_intermediate_timeout'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1255: undefined reference to `knox_collect_conntrack_data'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1324: undefined reference to `check_ncm_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/netfilter/nf_conntrack_core.c:1324: undefined reference to `check_intermediate_flag'
  net/ipv4/udp.o: In function `__udp4_lib_rcv':
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2295: undefined reference to `check_ncm_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2305: undefined reference to `check_intermediate_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2307: undefined reference to `get_intermediate_timeout'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2361: undefined reference to `check_ncm_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2371: undefined reference to `check_intermediate_flag'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2373: undefined reference to `get_intermediate_timeout'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2334: undefined reference to `knox_collect_conntrack_data'
  /home/hendra/Androwee/NetHunter/r8q/out/../net/ipv4/udp.c:2400: undefined reference to `knox_collect_conntrack_data'
  make[1]: *** [/home/hendra/Androwee/NetHunter/r8q/Makefile:1173: vmlinux] Error 1

These functions are only available when KNOX NCM is set,
so add the guards to use these functions only when
KNOX NCM is set.

Signed-off-by: Hendra Manudinata <hendra@manudinata.me>